#######################################################################################
#   
#   Author      :   Mark Monterosso
#   Date        :   23 Mar 20
#   
#   Description :   Role to support infrastructure provisioning in VM Workstation
#                   Execute tasks specific to Red Hat implementations    
#   
#   Dependencies:  Functional and accessible Red hat system
#                   
#######################################################################################

#--------------------------------------------------------------------------------------
#
# Workflow:
#
#--------------------------------------------------------------------------------------
---

- name:             "Updating Packages"
  yum:
    name: '*'
    state: latest

- name:             "Setting Hostname to {{ item.name }}" 
  hostname:
    name:           "{{ item.name }}"
    use:            "{{ ansible_os_family | lower }}"

- name:             "Updating Resolv.conf Settings"
  template:
    src:            resolv_template
    dest:           "/etc/resolv.conf"
    owner:          root
    group:          root
    mode:           '0644'

- name:             "Updating Resolv.conf Settings"
  template:
    src:            resolv_template
    dest:           "/etc/resolv.conf"
    owner:          root
    group:          root
    mode:           '0644'

- name:             "Updating Interface Settings"
  template:
    src:            /redhat/interface_template
    dest:           "/etc/sysconfig/network-sripts/{{}}"
    owner:          root
    group:          root
    mode:           '0644'
