#######################################################################################
#   
#   Author      :   Mark Monterosso
#   Date        :   23 Mar 20
#   
#   Description :   Role to support infrastructure provisioning in VM Workstation
#                   Execute tasks specific to Red Hat implementations    
#   
#   Dependencies:  Functional and accessible Red hat system
#                   
#######################################################################################

#--------------------------------------------------------------------------------------
#
# Workflow:
#
#--------------------------------------------------------------------------------------
---

- name:             "Updating Packages"
  yum:
    name:           '*'
    state:          latest

- name:             "Setting Hostname to {{ item.name }}" 
  hostname:
    name:           "{{ item.name }}"
    use:            "{{ ansible_os_family | lower }}"

- name:             "Updating Resolv.conf Settings"
  template:
    src:            resolv_template
    dest:           "/etc/resolv.conf"
    owner:          root
    group:          root
    mode:           '0644'

- name:             "Updating /etc/hosts File"
  template:
    src:            hosts_template
    dest:           "/etc/hosts"
    owner:          root
    group:          root
    mode:           '0644'

- name:             "Updating Interface Settings"
  template:
    src:            ./redhat/interface_template
    dest:           "/etc/sysconfig/network-scripts/{{ item.interface_name }}"
    owner:          root
    group:          root
    mode:           '0644'

- name: Reboot EC2 instance.
    shell: sleep 5 && shutdown -r now "Reboot triggered by Ansible script"
    async: 1
    poll: 0
    become: true
    tags:
      - reboot

  - name: Wait for instance reboot.
    local_action:
      module: wait_for
        host={{ item.static_ip }}
        port=22
        delay=15
        timeout=120
        state=started
    become: false