#######################################################################################
#   
#   Author      :   Mark Monterosso - Mark.Monterosso@NetApp.com
#   Date        :   23 Mar 20
#   
#   Description :   Role to support infrastructure provisioning in VM Workstation
#                   Execute tasks specific to Red Hat implementations    
#   
#   Dependencies:  
#                   
#######################################################################################

#--------------------------------------------------------------------------------------
#
# Workflow:
#
#--------------------------------------------------------------------------------------
---

- name: "Running plays for {{ ansible_os_family }} OS"
- hostname:
    name: web01


- debug:
    msg: "{{ inventory_hostname }} - You are redhat"