#######################################################################################
#   
#   Author      :   Mark Monterosso
#   Date        :   20 Apr 20
#   
#   Description :  
#                   
#   Dependencies:   
#                   
#######################################################################################

#--------------------------------------------------------------------------------------
#
# Workflow:
#
#--------------------------------------------------------------------------------------
---

- include:          add_cluster.yml
  when:             "( export_policy.operation | lower ) == 'add'"

- include:          remove_cluster.yml
  when:             "( export_policy.operation | lower ) == 'remove'"