#######################################################################################
#   
#   Author      :   Mark Monterosso
#   Date        :   20 Apr 20
#   
#   Description :  
#                   
#   Dependencies:   
#                   
#######################################################################################

#--------------------------------------------------------------------------------------
#
# Workflow:
#
#--------------------------------------------------------------------------------------
---
- include_tasks:            create.yml
  when:                     "( cifs_share.operation | lower ) == 'create'"


- include_tasks:            delete.yml
  when:                     "( cifs_share.operation | lower ) == 'delete'"
