#######################################################################################
#   
#   Author      :   Mark Monterosso
#   Date        :   23 Mar 20
#   
#   Description :   The purpose of this code is to facilitate cloning of virtual
#                   machines in VM Workstation
#   
#   Dependencies:   VM Workstation 15.x or Fusion 11
#                   
#######################################################################################
#--------------------------------------------------------------------------------------
#
# Workflow:
#   + Remove all VMs 
#
#--------------------------------------------------------------------------------------
---

- hosts:                        all
  name:                         Removing Lab Infrastructure
  gather_facts:                 false

  vars_files:
    -                           [ 'vars-provision-infra.yml' ]

  tasks:
    - name:                     "Deleting Virtual Machines"
      include_role:
        name:                   vmware/delete_vm_clones
      vars:
        vm_name:                "{{ item[1].name }}"
      with_subelements:                     
          -                     "{{ deployment }}"
          -                     vms
      when:
          -                     deployment is defined