#######################################################################################
#   
#   Author      :   Mark Monterosso
#   Date        :   23 Mar 20
#   
#   Description :   Role to support infrastructure provisioning in VM Workstation
#                   Deterimes the correct playbook to execute based on OS family
#   
#   Dependencies:   
#                   
#######################################################################################

#--------------------------------------------------------------------------------------
#
# Workflow:
#
#--------------------------------------------------------------------------------------
---

- include:          win2019.yml
  #when:             ansible_os_family == 'RedHat'

