#######################################################################################
#   
#   Author      :   Mark Monterosso
#   Date        :   23 Mar 20
#   
#   Description :   The purpose of this code is to facilitate cloning of virtual
#                   machines in VM Workstation
#   
#   Dependencies:   VM Workstation 15.x or Fusion 11
#                   
#######################################################################################

#--------------------------------------------------------------------------------------
#
# Workflow:
#   + Invoke role to create VM clones
#   + Invoke role to deploy base configurations 
#
#--------------------------------------------------------------------------------------
---

- hosts:                        localhost
  name:                         Creating and Powering on Virtual Environments
  gather_facts:                 true

  vars_files:
    -                           [ 'vars-provision-infra.yml' ]

  tasks:
   - name:                      "Creating Clones"
     include_role:
        name:                   create_vm_clones
     vars:
        vm_vars:                "{{ item }}"
     loop:                      "{{ deploy_vm_hosts }}" 
     when:
        -                       deploy_vm_hosts is defined

   - name:                      "Applying Base Host Configurations"
     include_role:
        name:                   apply_base_host_configs
     vars:
        vm_vars:                "{{ item }}"
     loop:                      "{{ deploy_vm_hosts }}" 
     when:
        -                       deploy_vm_hosts is defined
        -                       inventory_hostname is in ['tmp_ip_grp']