#######################################################################################
#   
#   Author      :   Mark Monterosso
#   Date        :   20 Apr 20
#   
#   Description :                 
#   
#   Dependencies:   
#                   
#######################################################################################

operation:                        "{{ operation }}"

deployment:
    - type:                       "{{ type }}" 
      vms:
        - name:                   "{{ name }}"
          vm_os_template:         "{{ vm_os_template }}"
          static_ip:              "{{ static_ip }}"
          gateway:                "{{ gateway }}"
          subnet:                 "{{ subnet }}"
          dns:                    "{{ dns }}"
          search_domain:          "{{ search_domain }}"
          interface_name:         "{{ interface_name }}"

          cluster_name:           "{{ cluster_name }}"
          cluster_mgmt_ip:        "{{ cluster_mgmt_ip }}"
          cluster_mgmt_netmask:   "{{ cluster_mgmt_netmask }}"
          node_ips:               "{{ node_ips }}"
