#######################################################################################
#   
#   Author      :   Mark Monterosso
#   Date        :   20 Apr 20
#   
#   Description :  
#                   
#   Dependencies:   
#                   
#######################################################################################

#--------------------------------------------------------------------------------------
#
# Workflow:
#
#--------------------------------------------------------------------------------------
---

- include:          create.yml
  when:             "( lif.operation | lower ) == 'create'"

- include:          delete.yml
  when:             "( lif.operation | lower ) == 'delete'"